%							----------------------------------
%							|Copyright : Kopsinis Yannis     |
%							|            Pikrakis Aggelos    |
%							|            Basilas Stratos     |
%							|           -------------------- |
%							|           Dept. of Informatics |
%							|           University of Athens |
%							----------------------------------
%%
% Sliders
global numclass figt3
numclass=2;
gcf=figure(figt3);
 


drawnow
sx1=0.1;
sy1=0.1;
sxy1=0;
sx2=0.1;
sy2=0.1;
sxy2=0;
p=20;

% s1 = 0.01;
% p = 20;
% s2 = 0.01;
% shape1 = [s1 p];
[plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);
nc = uicontrol('style','slider','units','normal','pos',[.01 .8 .1 .035], ...
     'min',0,'max',1,'val',sx1, ...
     'call',[...
     'set(nct,''string'',[''sx1: '',num2str(get(nc,''val''))]),',...     
     'sx1 = get(nc,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);

nct = uicontrol('style','text','units','normal','pos',[.01 .84 .1 .035], ...
     'string',['sx1: ',num2str(get(nc,'value'))]);

 
 nc2 = uicontrol('style','slider','units','normal','pos',[.01 .7 .1 .035], ...
     'min',0,'max',1,'val',sx2, ...
     'call',[...
     'set(nct2,''string'',[''sx2 : '',num2str(get(nc2,''val''))]),',...     
     'sx2 = get(nc2,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);

nct2 = uicontrol('style','text','units','normal','pos',[.01 .74 .1 .035], ...
     'string',['sx2 : ',num2str(get(nc2,'value'))]);

 nc3 = uicontrol('style','slider','units','normal','pos',[.01 .6 .1 .035], ...
     'min',0,'max',1,'val',sy1, ...
     'call',[...
     'set(nct3,''string'',[''sy1 : '',num2str(get(nc3,''val''))]),',...     
     'sy1 = get(nc3,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);

nct3 = uicontrol('style','text','units','normal','pos',[.01 .64 .1 .035], ...
     'string',['sy1: ',num2str(get(nc3,'value'))]);

 
 nc4 = uicontrol('style','slider','units','normal','pos',[.01 .5 .1 .035], ...
     'min',0,'max',1,'val',sy2, ...
     'call',[...
     'set(nct4,''string'',[''sy2 : '',num2str(get(nc4,''val''))]),',...     
     'sy2 = get(nc4,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);

nct4 = uicontrol('style','text','units','normal','pos',[.01 .54 .1 .035], ...
     'string',['sy2 : ',num2str(get(nc4,'value'))]);

 
 nc5 = uicontrol('style','slider','units','normal','pos',[.01 .4 .1 .035], ...
     'min',-1,'max',1,'val',sxy1, ...
     'call',[...
     'set(nct5,''string'',[''sxy1 : '',num2str(get(nc5,''val''))]),',...     
     'sxy1 = get(nc5,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);

nct5 = uicontrol('style','text','units','normal','pos',[.01 .44 .1 .035], ...
     'string',['sxy1 : ',num2str(get(nc5,'value'))]);
 
 nc6= uicontrol('style','slider','units','normal','pos',[.01 .3 .1 .035], ...
     'min',-1,'max',1,'val',sxy2, ...
     'call',[...
     'set(nct6,''string'',[''sxy2 : '',num2str(get(nc6,''val''))]),',...     
     'sxy2 = get(nc6,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);

nct6 = uicontrol('style','text','units','normal','pos',[.01 .34 .1 .035], ...
     'string',['sxy2 : ',num2str(get(nc6,'value'))]);
 
  
 
ec = uicontrol('style','slider','units','normal','pos',[.70 .00 .1 .035], ...
     'min',5,'max',100,'val',p, ...
     'call',[...
     'k=get(ec,''val'');,',...  
     'set(ect,''string'',[''patterns : '',num2str(round(k))]),',...     
     'p = get(ec,''value''); [plithos,metrisis]=ransettest(sx1,sy1,sxy1,sx2,sy2,sxy2,p);']);
ect = uicontrol('style','text','units','normal','pos',[.725 .057 .2 .05], ...
     'string',['patterns : ',num2str(round(get(ec,'value')))]);

 
 
 
p=round(p);

